const { Product } = require('./models');
const { sequelize } = require('./models');

// Real tea products dataset with varieties
const teaProducts = [
  // BLACK TEAS
  {
    name: "Assam Golden Tips",
    description: "Premium black tea from Assam, India with golden tips. Rich, malty flavor with notes of caramel and honey. Perfect for morning.",
    price: 18.99,
    stockQuantity: 150,
    category: "Black Tea",
    imageUrl: "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "100g",
    packetSizeGrams: 100,
    isImported: true,
    shippingDays: 12,
    originCountry: "India",
    sku: "BT-ASSAM-GT-100",
    warehouseStock: 150,
    reorderLevel: 20,
    purchaseCost: 9.50,
    profitMargin: 50.00
  },
  {
    name: "Ceylon Orange Pekoe",
    description: "Classic Sri Lankan black tea with bright, crisp flavor. Medium-bodied with citrus notes. Excellent hot or iced.",
    price: 15.99,
    stockQuantity: 200,
    category: "Black Tea",
    imageUrl: "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "100g",
    packetSizeGrams: 100,
    isImported: true,
    shippingDays: 14,
    originCountry: "Sri Lanka",
    sku: "BT-CEYLON-OP-100",
    warehouseStock: 200,
    reorderLevel: 30,
    purchaseCost: 8.00,
    profitMargin: 50.00
  },
  {
    name: "English Breakfast Blend",
    description: "Robust blend of Assam and Ceylon teas. Full-bodied and malty. Perfect with milk and sugar. Morning favorite.",
    price: 12.99,
    stockQuantity: 300,
    category: "Black Tea",
    imageUrl: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400",
    isActive: true,
    teaType: "both",
    packetSize: "50 bags",
    packetSizeGrams: 100,
    isImported: false,
    shippingDays: 3,
    originCountry: "USA",
    sku: "BT-ENGBF-50B",
    warehouseStock: 300,
    reorderLevel: 50,
    purchaseCost: 6.50,
    profitMargin: 50.00
  },
  {
    name: "Earl Grey Supreme",
    description: "Premium black tea scented with bergamot oil. Elegant citrus aroma. Classic afternoon tea. Sophisticated flavor.",
    price: 14.99,
    stockQuantity: 250,
    category: "Black Tea",
    imageUrl: "https://images.unsplash.com/photo-1558160074-4d7d8bdf4256?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "100g",
    packetSizeGrams: 100,
    isImported: false,
    shippingDays: 3,
    originCountry: "USA",
    sku: "BT-EARLG-100",
    warehouseStock: 250,
    reorderLevel: 40,
    purchaseCost: 7.50,
    profitMargin: 50.00
  },
  {
    name: "Darjeeling First Flush",
    description: "Spring harvest from Darjeeling, India. Delicate, floral, muscatel notes. Light-bodied. Tea connoisseur favorite.",
    price: 24.99,
    stockQuantity: 100,
    category: "Black Tea",
    imageUrl: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "50g",
    packetSizeGrams: 50,
    isImported: true,
    shippingDays: 15,
    originCountry: "India",
    sku: "BT-DARJ-FF-50",
    warehouseStock: 100,
    reorderLevel: 15,
    purchaseCost: 12.50,
    profitMargin: 50.00
  },

  // GREEN TEAS
  {
    name: "Sencha Premium",
    description: "Japanese steamed green tea. Fresh, grassy flavor with sweet finish. Rich in antioxidants. Daily health tea.",
    price: 16.99,
    stockQuantity: 180,
    category: "Green Tea",
    imageUrl: "https://images.unsplash.com/photo-1627435601361-ec25f5b1d0e5?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "100g",
    packetSizeGrams: 100,
    isImported: true,
    shippingDays: 16,
    originCountry: "Japan",
    sku: "GT-SENCH-100",
    warehouseStock: 180,
    reorderLevel: 25,
    purchaseCost: 8.50,
    profitMargin: 50.00
  },
  {
    name: "Matcha Ceremonial Grade",
    description: "Premium stone-ground matcha powder. Vibrant green, smooth umami flavor. Perfect for tea ceremony or lattes.",
    price: 28.99,
    stockQuantity: 80,
    category: "Green Tea",
    imageUrl: "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "30g",
    packetSizeGrams: 30,
    isImported: true,
    shippingDays: 18,
    originCountry: "Japan",
    sku: "GT-MATCH-CG-30",
    warehouseStock: 80,
    reorderLevel: 10,
    purchaseCost: 14.50,
    profitMargin: 50.00
  },
  {
    name: "Dragon Well (Longjing)",
    description: "Famous Chinese green tea from Hangzhou. Flat leaves, sweet, nutty flavor. One of China's top ten teas.",
    price: 22.99,
    stockQuantity: 120,
    category: "Green Tea",
    imageUrl: "https://images.unsplash.com/photo-1563822249366-757dea7696d7?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "50g",
    packetSizeGrams: 50,
    isImported: true,
    shippingDays: 14,
    originCountry: "China",
    sku: "GT-DRAGW-50",
    warehouseStock: 120,
    reorderLevel: 15,
    purchaseCost: 11.50,
    profitMargin: 50.00
  },
  {
    name: "Moroccan Mint Green Tea",
    description: "Green tea with spearmint. Refreshing, cooling. Traditional North African blend. Great iced or hot.",
    price: 13.99,
    stockQuantity: 200,
    category: "Green Tea",
    imageUrl: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400",
    isActive: true,
    teaType: "both",
    packetSize: "50 bags",
    packetSizeGrams: 75,
    isImported: false,
    shippingDays: 3,
    originCountry: "USA",
    sku: "GT-MRMINT-50B",
    warehouseStock: 200,
    reorderLevel: 35,
    purchaseCost: 7.00,
    profitMargin: 50.00
  },
  {
    name: "Jasmine Pearl",
    description: "Hand-rolled green tea pearls scented with jasmine flowers. Delicate floral aroma. Visually stunning. Special occasions.",
    price: 19.99,
    stockQuantity: 150,
    category: "Green Tea",
    imageUrl: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "50g",
    packetSizeGrams: 50,
    isImported: true,
    shippingDays: 12,
    originCountry: "China",
    sku: "GT-JASPR-50",
    warehouseStock: 150,
    reorderLevel: 20,
    purchaseCost: 10.00,
    profitMargin: 50.00
  },

  // OOLONG TEAS
  {
    name: "Tie Guan Yin (Iron Goddess)",
    description: "Premium Chinese oolong. Complex flavor, orchid aroma. Multiple infusions. Highly prized tea variety.",
    price: 26.99,
    stockQuantity: 90,
    category: "Oolong Tea",
    imageUrl: "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "50g",
    packetSizeGrams: 50,
    isImported: true,
    shippingDays: 15,
    originCountry: "China",
    sku: "OT-TIEGN-50",
    warehouseStock: 90,
    reorderLevel: 12,
    purchaseCost: 13.50,
    profitMargin: 50.00
  },
  {
    name: "Formosa Oolong",
    description: "Taiwanese high mountain oolong. Smooth, creamy texture. Honey notes. Award-winning tea gardens.",
    price: 29.99,
    stockQuantity: 70,
    category: "Oolong Tea",
    imageUrl: "https://images.unsplash.com/photo-1597318130239-6d5b17660321?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "50g",
    packetSizeGrams: 50,
    isImported: true,
    shippingDays: 16,
    originCountry: "Taiwan",
    sku: "OT-FORMO-50",
    warehouseStock: 70,
    reorderLevel: 10,
    purchaseCost: 15.00,
    profitMargin: 50.00
  },
  {
    name: "Milk Oolong",
    description: "Taiwanese oolong with natural milky aroma. Creamy mouthfeel. No dairy. Unique cultivar characteristic.",
    price: 21.99,
    stockQuantity: 110,
    category: "Oolong Tea",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "75g",
    packetSizeGrams: 75,
    isImported: true,
    shippingDays: 14,
    originCountry: "Taiwan",
    sku: "OT-MILKO-75",
    warehouseStock: 110,
    reorderLevel: 15,
    purchaseCost: 11.00,
    profitMargin: 50.00
  },
  {
    name: "Da Hong Pao (Big Red Robe)",
    description: "Legendary Wuyi rock oolong. Roasted, mineral notes. Complex depth. One of China's most famous teas.",
    price: 32.99,
    stockQuantity: 60,
    category: "Oolong Tea",
    imageUrl: "https://images.unsplash.com/photo-1582793988951-9aed5509eb97?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "50g",
    packetSizeGrams: 50,
    isImported: true,
    shippingDays: 17,
    originCountry: "China",
    sku: "OT-DAHNG-50",
    warehouseStock: 60,
    reorderLevel: 8,
    purchaseCost: 16.50,
    profitMargin: 50.00
  },

  // WHITE TEAS
  {
    name: "Silver Needle (Bai Hao Yinzhen)",
    description: "Premium white tea from Fujian, China. Delicate, sweet, subtle. Minimally processed. Rare and expensive.",
    price: 34.99,
    stockQuantity: 50,
    category: "White Tea",
    imageUrl: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "30g",
    packetSizeGrams: 30,
    isImported: true,
    shippingDays: 16,
    originCountry: "China",
    sku: "WT-SILVN-30",
    warehouseStock: 50,
    reorderLevel: 7,
    purchaseCost: 17.50,
    profitMargin: 50.00
  },
  {
    name: "White Peony (Bai Mudan)",
    description: "Chinese white tea with buds and leaves. Slightly stronger than Silver Needle. Floral, fruity notes.",
    price: 24.99,
    stockQuantity: 80,
    category: "White Tea",
    imageUrl: "https://images.unsplash.com/photo-1577968897966-3d4325b36f61?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "50g",
    packetSizeGrams: 50,
    isImported: true,
    shippingDays: 15,
    originCountry: "China",
    sku: "WT-WHIPE-50",
    warehouseStock: 80,
    reorderLevel: 10,
    purchaseCost: 12.50,
    profitMargin: 50.00
  },

  // PU-ERH TEAS
  {
    name: "Pu-erh Ripe (Shou)",
    description: "Aged fermented tea from Yunnan. Earthy, smooth. Aids digestion. Improves with age. Dark liquor.",
    price: 19.99,
    stockQuantity: 100,
    category: "Pu-erh Tea",
    imageUrl: "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "100g",
    packetSizeGrams: 100,
    isImported: true,
    shippingDays: 13,
    originCountry: "China",
    sku: "PT-RIPE-100",
    warehouseStock: 100,
    reorderLevel: 15,
    purchaseCost: 10.00,
    profitMargin: 50.00
  },
  {
    name: "Pu-erh Raw (Sheng)",
    description: "Unfermented pu-erh. Green, fresh when young. Ages beautifully. Investment-grade tea. Complex flavor development.",
    price: 27.99,
    stockQuantity: 70,
    category: "Pu-erh Tea",
    imageUrl: "https://images.unsplash.com/photo-1597999987901-c6d52f948b19?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "100g",
    packetSizeGrams: 100,
    isImported: true,
    shippingDays: 14,
    originCountry: "China",
    sku: "PT-RAW-100",
    warehouseStock: 70,
    reorderLevel: 10,
    purchaseCost: 14.00,
    profitMargin: 50.00
  },

  // HERBAL & ROOIBOS
  {
    name: "Chamomile Flowers",
    description: "Egyptian chamomile flowers. Calming, soothing. Natural sleep aid. Sweet apple-like flavor. Caffeine-free.",
    price: 11.99,
    stockQuantity: 220,
    category: "Herbal Tea",
    imageUrl: "https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "50g",
    packetSizeGrams: 50,
    isImported: true,
    shippingDays: 11,
    originCountry: "Egypt",
    sku: "HT-CHAMO-50",
    warehouseStock: 220,
    reorderLevel: 30,
    purchaseCost: 6.00,
    profitMargin: 50.00
  },
  {
    name: "Peppermint Leaves",
    description: "Pure peppermint leaves. Refreshing, cooling. Digestive support. Naturally caffeine-free. Strong menthol flavor.",
    price: 10.99,
    stockQuantity: 250,
    category: "Herbal Tea",
    imageUrl: "https://images.unsplash.com/photo-1542990253-a781e04c0082?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "75g",
    packetSizeGrams: 75,
    isImported: false,
    shippingDays: 3,
    originCountry: "USA",
    sku: "HT-PEPMT-75",
    warehouseStock: 250,
    reorderLevel: 40,
    purchaseCost: 5.50,
    profitMargin: 50.00
  },
  {
    name: "Rooibos Red Bush",
    description: "South African rooibos. Naturally sweet, nutty. Rich in antioxidants. Caffeine-free. Kids love it.",
    price: 12.99,
    stockQuantity: 200,
    category: "Herbal Tea",
    imageUrl: "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "100g",
    packetSizeGrams: 100,
    isImported: true,
    shippingDays: 18,
    originCountry: "South Africa",
    sku: "HT-ROOIB-100",
    warehouseStock: 200,
    reorderLevel: 30,
    purchaseCost: 6.50,
    profitMargin: 50.00
  },
  {
    name: "Ginger Turmeric Blend",
    description: "Spicy ginger with turmeric. Anti-inflammatory properties. Warming. Immune support. Caffeine-free wellness tea.",
    price: 13.99,
    stockQuantity: 180,
    category: "Herbal Tea",
    imageUrl: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "75g",
    packetSizeGrams: 75,
    isImported: false,
    shippingDays: 3,
    originCountry: "USA",
    sku: "HT-GINTM-75",
    warehouseStock: 180,
    reorderLevel: 25,
    purchaseCost: 7.00,
    profitMargin: 50.00
  },
  {
    name: "Hibiscus Petals",
    description: "Bright red hibiscus. Tart, cranberry-like flavor. High in vitamin C. Iced tea favorite. Beautiful color.",
    price: 11.99,
    stockQuantity: 190,
    category: "Herbal Tea",
    imageUrl: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "75g",
    packetSizeGrams: 75,
    isImported: true,
    shippingDays: 12,
    originCountry: "Egypt",
    sku: "HT-HIBIS-75",
    warehouseStock: 190,
    reorderLevel: 28,
    purchaseCost: 6.00,
    profitMargin: 50.00
  },

  // SPECIALTY BLENDS
  {
    name: "Masala Chai",
    description: "Indian spiced black tea. Cinnamon, cardamom, cloves, ginger. Perfect with milk. Warming and aromatic.",
    price: 14.99,
    stockQuantity: 170,
    category: "Black Tea",
    imageUrl: "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "100g",
    packetSizeGrams: 100,
    isImported: true,
    shippingDays: 11,
    originCountry: "India",
    sku: "BT-MASCH-100",
    warehouseStock: 170,
    reorderLevel: 25,
    purchaseCost: 7.50,
    profitMargin: 50.00
  },
  {
    name: "Russian Caravan",
    description: "Smoky black tea blend. Traditional recipe. Lapsang Souchong base. Campfire-like aroma. Bold character.",
    price: 16.99,
    stockQuantity: 130,
    category: "Black Tea",
    imageUrl: "https://images.unsplash.com/photo-1597481497515-2f0fc89c2a3e?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "100g",
    packetSizeGrams: 100,
    isImported: false,
    shippingDays: 3,
    originCountry: "USA",
    sku: "BT-RUSCA-100",
    warehouseStock: 130,
    reorderLevel: 20,
    purchaseCost: 8.50,
    profitMargin: 50.00
  },
  {
    name: "Lapsang Souchong",
    description: "Chinese smoked black tea. Pine wood smoke flavor. Unique, acquired taste. Whiskey-like notes. Bacon tea.",
    price: 17.99,
    stockQuantity: 100,
    category: "Black Tea",
    imageUrl: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "75g",
    packetSizeGrams: 75,
    isImported: true,
    shippingDays: 13,
    originCountry: "China",
    sku: "BT-LAPSA-75",
    warehouseStock: 100,
    reorderLevel: 15,
    purchaseCost: 9.00,
    profitMargin: 50.00
  },
  {
    name: "Lemon Ginger Green Tea",
    description: "Green tea with lemon and ginger. Refreshing, zesty. Immune-boosting. Perfect morning energizer. Natural flavors.",
    price: 13.99,
    stockQuantity: 200,
    category: "Green Tea",
    imageUrl: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400",
    isActive: true,
    teaType: "tea_bags",
    packetSize: "40 bags",
    packetSizeGrams: 80,
    isImported: false,
    shippingDays: 3,
    originCountry: "USA",
    sku: "GT-LEMGI-40B",
    warehouseStock: 200,
    reorderLevel: 35,
    purchaseCost: 7.00,
    profitMargin: 50.00
  },
  {
    name: "Berry Hibiscus",
    description: "Fruity herbal blend. Hibiscus, strawberry, blueberry. Sweet-tart. Beautiful pink color. Kids approved.",
    price: 12.99,
    stockQuantity: 190,
    category: "Herbal Tea",
    imageUrl: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400",
    isActive: true,
    teaType: "tea_bags",
    packetSize: "30 bags",
    packetSizeGrams: 60,
    isImported: false,
    shippingDays: 3,
    originCountry: "USA",
    sku: "HT-BERHB-30B",
    warehouseStock: 190,
    reorderLevel: 30,
    purchaseCost: 6.50,
    profitMargin: 50.00
  },

  // RARE & PREMIUM
  {
    name: "Gyokuro Shade-Grown",
    description: "Japan's finest green tea. Shade-grown for sweetness. Deep umami flavor. Emerald green liquor. Tea ceremony grade.",
    price: 39.99,
    stockQuantity: 40,
    category: "Green Tea",
    imageUrl: "https://images.unsplash.com/photo-1627435601361-ec25f5b1d0e5?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "30g",
    packetSizeGrams: 30,
    isImported: true,
    shippingDays: 19,
    originCountry: "Japan",
    sku: "GT-GYOKU-30",
    warehouseStock: 40,
    reorderLevel: 5,
    purchaseCost: 20.00,
    profitMargin: 50.00
  },
  {
    name: "Phoenix Dan Cong Oolong",
    description: "Single-bush oolong from Guangdong. Orchid, honey, stone fruit notes. Multiple steeping. Collectible tea.",
    price: 36.99,
    stockQuantity: 45,
    category: "Oolong Tea",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "50g",
    packetSizeGrams: 50,
    isImported: true,
    shippingDays: 16,
    originCountry: "China",
    sku: "OT-PHDCO-50",
    warehouseStock: 45,
    reorderLevel: 6,
    purchaseCost: 18.50,
    profitMargin: 50.00
  },
  {
    name: "Golden Monkey Black Tea",
    description: "Premium Fujian black tea. Chocolate, malt notes. Beautiful golden tips. Smooth, no astringency. Luxury daily tea.",
    price: 21.99,
    stockQuantity: 110,
    category: "Black Tea",
    imageUrl: "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "75g",
    packetSizeGrams: 75,
    isImported: true,
    shippingDays: 14,
    originCountry: "China",
    sku: "BT-GOLDM-75",
    warehouseStock: 110,
    reorderLevel: 18,
    purchaseCost: 11.00,
    profitMargin: 50.00
  },
  {
    name: "Keemun Black Tea",
    description: "Chinese congou black tea. Wine-like, orchid fragrance. Smooth, slightly sweet. Low astringency. Breakfast tea.",
    price: 17.99,
    stockQuantity: 140,
    category: "Black Tea",
    imageUrl: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "100g",
    packetSizeGrams: 100,
    isImported: true,
    shippingDays: 12,
    originCountry: "China",
    sku: "BT-KEEMU-100",
    warehouseStock: 140,
    reorderLevel: 22,
    purchaseCost: 9.00,
    profitMargin: 50.00
  },
  {
    name: "Yunnan Golden Needles",
    description: "Pure golden buds from Yunnan. Honey-sweet, malty. No bitterness. Luxury Chinese black tea. Beautiful appearance.",
    price: 23.99,
    stockQuantity: 95,
    category: "Black Tea",
    imageUrl: "https://images.unsplash.com/photo-1597318130239-6d5b17660321?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "50g",
    packetSizeGrams: 50,
    isImported: true,
    shippingDays: 13,
    originCountry: "China",
    sku: "BT-YNGOL-50",
    warehouseStock: 95,
    reorderLevel: 14,
    purchaseCost: 12.00,
    profitMargin: 50.00
  },

  // FLAVORED TEAS
  {
    name: "Peach Oolong",
    description: "Oolong tea with peach flavor. Sweet, fruity. Natural flavoring. Delicious hot or iced. Summer favorite.",
    price: 15.99,
    stockQuantity: 160,
    category: "Oolong Tea",
    imageUrl: "https://images.unsplash.com/photo-1597999987901-c6d52f948b19?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "75g",
    packetSizeGrams: 75,
    isImported: false,
    shippingDays: 3,
    originCountry: "USA",
    sku: "OT-PEACH-75",
    warehouseStock: 160,
    reorderLevel: 25,
    purchaseCost: 8.00,
    profitMargin: 50.00
  },
  {
    name: "Vanilla Rooibos",
    description: "Rooibos with vanilla. Naturally sweet, dessert-like. Caffeine-free. Creamy flavor. Evening relaxation tea.",
    price: 13.99,
    stockQuantity: 175,
    category: "Herbal Tea",
    imageUrl: "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "100g",
    packetSizeGrams: 100,
    isImported: false,
    shippingDays: 3,
    originCountry: "USA",
    sku: "HT-VANRO-100",
    warehouseStock: 175,
    reorderLevel: 28,
    purchaseCost: 7.00,
    profitMargin: 50.00
  },
  {
    name: "Chocolate Mint Pu-erh",
    description: "Pu-erh with chocolate and mint. Decadent, refreshing. Natural flavors. After-dinner treat. Unique combination.",
    price: 18.99,
    stockQuantity: 120,
    category: "Pu-erh Tea",
    imageUrl: "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "75g",
    packetSizeGrams: 75,
    isImported: false,
    shippingDays: 3,
    originCountry: "USA",
    sku: "PT-CHOMI-75",
    warehouseStock: 120,
    reorderLevel: 20,
    purchaseCost: 9.50,
    profitMargin: 50.00
  },
  {
    name: "Lavender Earl Grey",
    description: "Earl Grey with lavender flowers. Floral, sophisticated. Calming bergamot-lavender blend. Afternoon delight.",
    price: 16.99,
    stockQuantity: 145,
    category: "Black Tea",
    imageUrl: "https://images.unsplash.com/photo-1558160074-4d7d8bdf4256?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "75g",
    packetSizeGrams: 75,
    isImported: false,
    shippingDays: 3,
    originCountry: "USA",
    sku: "BT-LAVEG-75",
    warehouseStock: 145,
    reorderLevel: 23,
    purchaseCost: 8.50,
    profitMargin: 50.00
  },
  {
    name: "Apple Cinnamon Black Tea",
    description: "Black tea with apple and cinnamon. Warm, cozy flavor. Fall favorite. Natural spices. Pairs with desserts.",
    price: 14.99,
    stockQuantity: 185,
    category: "Black Tea",
    imageUrl: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400",
    isActive: true,
    teaType: "tea_bags",
    packetSize: "40 bags",
    packetSizeGrams: 80,
    isImported: false,
    shippingDays: 3,
    originCountry: "USA",
    sku: "BT-APCIN-40B",
    warehouseStock: 185,
    reorderLevel: 30,
    purchaseCost: 7.50,
    profitMargin: 50.00
  },

  // WELLNESS TEAS
  {
    name: "Detox Dandelion Root",
    description: "Roasted dandelion root. Liver support. Coffee alternative. Earthy, slightly bitter. Wellness tea.",
    price: 12.99,
    stockQuantity: 140,
    category: "Herbal Tea",
    imageUrl: "https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "100g",
    packetSizeGrams: 100,
    isImported: false,
    shippingDays: 3,
    originCountry: "USA",
    sku: "HT-DANDA-100",
    warehouseStock: 140,
    reorderLevel: 22,
    purchaseCost: 6.50,
    profitMargin: 50.00
  },
  {
    name: "Echinacea Immune Boost",
    description: "Echinacea with elderberry. Immune system support. Berry flavor. Cold and flu season essential. Herbal remedy.",
    price: 14.99,
    stockQuantity: 155,
    category: "Herbal Tea",
    imageUrl: "https://images.unsplash.com/photo-1542990253-a781e04c0082?w=400",
    isActive: true,
    teaType: "tea_bags",
    packetSize: "30 bags",
    packetSizeGrams: 60,
    isImported: false,
    shippingDays: 3,
    originCountry: "USA",
    sku: "HT-ECHIM-30B",
    warehouseStock: 155,
    reorderLevel: 25,
    purchaseCost: 7.50,
    profitMargin: 50.00
  },
  {
    name: "Sleep & Relax Blend",
    description: "Chamomile, valerian, passionflower. Natural sleep aid. Calming, soothing. Bedtime ritual. Stress relief.",
    price: 13.99,
    stockQuantity: 170,
    category: "Herbal Tea",
    imageUrl: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400",
    isActive: true,
    teaType: "tea_bags",
    packetSize: "30 bags",
    packetSizeGrams: 45,
    isImported: false,
    shippingDays: 3,
    originCountry: "USA",
    sku: "HT-SLEEP-30B",
    warehouseStock: 170,
    reorderLevel: 27,
    purchaseCost: 7.00,
    profitMargin: 50.00
  },
  {
    name: "Turmeric Wellness Tea",
    description: "Turmeric, ginger, black pepper. Anti-inflammatory. Golden milk base. Health benefits. Daily wellness routine.",
    price: 15.99,
    stockQuantity: 165,
    category: "Herbal Tea",
    imageUrl: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=400",
    isActive: true,
    teaType: "loose_leaf",
    packetSize: "100g",
    packetSizeGrams: 100,
    isImported: false,
    shippingDays: 3,
    originCountry: "USA",
    sku: "HT-TURWE-100",
    warehouseStock: 165,
    reorderLevel: 26,
    purchaseCost: 8.00,
    profitMargin: 50.00
  }
];

async function seedDatabase() {
  try {
    console.log('🌱 Starting tea products seed...');

    // Test database connection
    await sequelize.authenticate();
    console.log('✅ Database connection established');

    // Sync models
    await sequelize.sync();
    console.log('✅ Database models synchronized');

    // Clear existing products (optional - comment out if you want to keep existing)
    // await Product.destroy({ where: {} });
    // console.log('🗑️  Cleared existing products');

    // Insert products
    console.log(`📦 Inserting ${teaProducts.length} tea products...`);

    for (const product of teaProducts) {
      await Product.create(product);
      console.log(`   ✓ Added: ${product.name} (${product.category})`);
    }

    console.log('\n✅ Successfully seeded database with tea products!');
    console.log(`📊 Total products added: ${teaProducts.length}`);
    console.log('\nBreakdown by category:');
    console.log(`   Black Tea: ${teaProducts.filter(p => p.category === 'Black Tea').length}`);
    console.log(`   Green Tea: ${teaProducts.filter(p => p.category === 'Green Tea').length}`);
    console.log(`   Oolong Tea: ${teaProducts.filter(p => p.category === 'Oolong Tea').length}`);
    console.log(`   White Tea: ${teaProducts.filter(p => p.category === 'White Tea').length}`);
    console.log(`   Pu-erh Tea: ${teaProducts.filter(p => p.category === 'Pu-erh Tea').length}`);
    console.log(`   Herbal Tea: ${teaProducts.filter(p => p.category === 'Herbal Tea').length}`);

    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
}

// Run the seed function
seedDatabase();
