require('dotenv').config();
const { Product, sequelize } = require('./models');

const teaProducts = [
  // Japanese Green Teas (Imported)
  {
    name: 'Sencha Supreme',
    description: 'Classic Japanese green tea with a refreshing, grassy flavor and sweet finish. Steamed to perfection.',
    price: 18.99,
    stockQuantity: 45,
    category: 'Green Tea',
    imageUrl: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400',
    teaType: 'loose_leaf',
    packetSize: '100g',
    packetSizeGrams: 100,
    isImported: true,
    shippingDays: 12,
    originCountry: 'Japan',
    sku: 'JP-SENCHA-100',
    barcode: '8901234567001',
    warehouseStock: 50,
    reorderLevel: 15,
    purchaseCost: 9.50,
    profitMargin: 99.89,
    isActive: true
  },
  {
    name: 'Matcha Ceremonial Grade',
    description: 'Premium ceremonial grade matcha powder from Uji, Japan. Vibrant green color with umami-rich taste.',
    price: 34.99,
    stockQuantity: 28,
    category: 'Green Tea',
    imageUrl: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=400',
    teaType: 'loose_leaf',
    packetSize: '30g',
    packetSizeGrams: 30,
    isImported: true,
    shippingDays: 12,
    originCountry: 'Japan',
    sku: 'JP-MATCHA-30',
    barcode: '8901234567002',
    warehouseStock: 30,
    reorderLevel: 10,
    purchaseCost: 17.00,
    profitMargin: 105.82,
    isActive: true
  },
  {
    name: 'Genmaicha Roasted Rice',
    description: 'Green tea blended with roasted brown rice. Nutty, toasty flavor with lower caffeine.',
    price: 14.99,
    stockQuantity: 62,
    category: 'Green Tea',
    imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400',
    teaType: 'loose_leaf',
    packetSize: '150g',
    packetSizeGrams: 150,
    isImported: true,
    shippingDays: 12,
    originCountry: 'Japan',
    sku: 'JP-GENMAI-150',
    barcode: '8901234567003',
    warehouseStock: 65,
    reorderLevel: 20,
    purchaseCost: 7.00,
    profitMargin: 114.14,
    isActive: true
  },
  {
    name: 'Hojicha Roasted Green Tea',
    description: 'Roasted Japanese green tea with caramel notes. Low caffeine, perfect for evening.',
    price: 16.50,
    stockQuantity: 38,
    category: 'Green Tea',
    imageUrl: 'https://images.unsplash.com/photo-1597318181390-8a9758586c85?w=400',
    teaType: 'tea_bags',
    packetSize: '20 bags',
    packetSizeGrams: 40,
    isImported: true,
    shippingDays: 12,
    originCountry: 'Japan',
    sku: 'JP-HOJI-20B',
    barcode: '8901234567004',
    warehouseStock: 40,
    reorderLevel: 15,
    purchaseCost: 8.00,
    profitMargin: 106.25,
    isActive: true
  },

  // Chinese Teas (Imported)
  {
    name: 'Dragonwell (Longjing) Premium',
    description: 'Famous Chinese green tea from Hangzhou. Sweet, mellow flavor with chestnut notes.',
    price: 26.99,
    stockQuantity: 34,
    category: 'Green Tea',
    imageUrl: 'https://images.unsplash.com/photo-1563822249366-3efbc8e9026d?w=400',
    teaType: 'loose_leaf',
    packetSize: '100g',
    packetSizeGrams: 100,
    isImported: true,
    shippingDays: 14,
    originCountry: 'China',
    sku: 'CN-DRAGON-100',
    barcode: '8901234567005',
    warehouseStock: 35,
    reorderLevel: 12,
    purchaseCost: 13.00,
    profitMargin: 107.62,
    isActive: true
  },
  {
    name: 'Pu-erh Aged Black Tea',
    description: '5-year aged Pu-erh from Yunnan. Earthy, smooth, and complex. Great for digestion.',
    price: 29.99,
    stockQuantity: 22,
    category: 'Black Tea',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400',
    teaType: 'loose_leaf',
    packetSize: '100g',
    packetSizeGrams: 100,
    isImported: true,
    shippingDays: 14,
    originCountry: 'China',
    sku: 'CN-PUERH-100',
    barcode: '8901234567006',
    warehouseStock: 25,
    reorderLevel: 10,
    purchaseCost: 15.00,
    profitMargin: 99.93,
    isActive: true
  },
  {
    name: 'Jasmine Dragon Pearls',
    description: 'Hand-rolled green tea pearls scented with fresh jasmine blossoms. Fragrant and elegant.',
    price: 22.99,
    stockQuantity: 41,
    category: 'Green Tea',
    imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400',
    teaType: 'loose_leaf',
    packetSize: '75g',
    packetSizeGrams: 75,
    isImported: true,
    shippingDays: 14,
    originCountry: 'China',
    sku: 'CN-JASMINE-75',
    barcode: '8901234567007',
    warehouseStock: 45,
    reorderLevel: 15,
    purchaseCost: 11.00,
    profitMargin: 109.00,
    isActive: true
  },
  {
    name: 'Tie Guan Yin Oolong',
    description: 'Iron Goddess of Mercy oolong. Floral, creamy, and sweet with orchid notes.',
    price: 24.99,
    stockQuantity: 31,
    category: 'Oolong Tea',
    imageUrl: 'https://images.unsplash.com/photo-1558160074-4d7d8bdf4256?w=400',
    teaType: 'loose_leaf',
    packetSize: '100g',
    packetSizeGrams: 100,
    isImported: true,
    shippingDays: 14,
    originCountry: 'China',
    sku: 'CN-TIEGUANYIN-100',
    barcode: '8901234567008',
    warehouseStock: 35,
    reorderLevel: 12,
    purchaseCost: 12.00,
    profitMargin: 108.25,
    isActive: true
  },

  // Indian Teas (Imported)
  {
    name: 'Darjeeling First Flush FTGFOP',
    description: 'The champagne of teas. Light, floral, muscatel flavor from Himalayan estates.',
    price: 32.99,
    stockQuantity: 26,
    category: 'Black Tea',
    imageUrl: 'https://images.unsplash.com/photo-1597318181390-8a9758586c85?w=400',
    teaType: 'loose_leaf',
    packetSize: '100g',
    packetSizeGrams: 100,
    isImported: true,
    shippingDays: 13,
    originCountry: 'India',
    sku: 'IN-DARJ-FF-100',
    barcode: '8901234567009',
    warehouseStock: 30,
    reorderLevel: 10,
    purchaseCost: 16.00,
    profitMargin: 106.19,
    isActive: true
  },
  {
    name: 'Assam Breakfast Blend',
    description: 'Bold, malty black tea perfect for morning. Strong enough for milk and sugar.',
    price: 15.99,
    stockQuantity: 78,
    category: 'Black Tea',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400',
    teaType: 'tea_bags',
    packetSize: '50 bags',
    packetSizeGrams: 100,
    isImported: true,
    shippingDays: 13,
    originCountry: 'India',
    sku: 'IN-ASSAM-50B',
    barcode: '8901234567010',
    warehouseStock: 80,
    reorderLevel: 25,
    purchaseCost: 7.50,
    profitMargin: 113.20,
    isActive: true
  },
  {
    name: 'Nilgiri Frost Tea',
    description: 'South Indian black tea with fruity, brisk character. Excellent iced tea.',
    price: 14.99,
    stockQuantity: 54,
    category: 'Black Tea',
    imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400',
    teaType: 'loose_leaf',
    packetSize: '150g',
    packetSizeGrams: 150,
    isImported: true,
    shippingDays: 13,
    originCountry: 'India',
    sku: 'IN-NILGIRI-150',
    barcode: '8901234567011',
    warehouseStock: 60,
    reorderLevel: 20,
    purchaseCost: 7.00,
    profitMargin: 114.14,
    isActive: true
  },
  {
    name: 'Masala Chai Spice Blend',
    description: 'Traditional Indian chai with cardamom, cinnamon, ginger, and cloves. Pre-blended.',
    price: 12.99,
    stockQuantity: 92,
    category: 'Black Tea',
    imageUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400',
    teaType: 'loose_leaf',
    packetSize: '200g',
    packetSizeGrams: 200,
    isImported: true,
    shippingDays: 13,
    originCountry: 'India',
    sku: 'IN-CHAI-200',
    barcode: '8901234567012',
    warehouseStock: 100,
    reorderLevel: 30,
    purchaseCost: 6.00,
    profitMargin: 116.50,
    isActive: true
  },

  // Ceylon Teas (Sri Lanka - Imported)
  {
    name: 'Ceylon Orange Pekoe',
    description: 'Bright, brisk Ceylon tea with citrus notes. Perfect afternoon tea.',
    price: 13.99,
    stockQuantity: 68,
    category: 'Black Tea',
    imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400',
    teaType: 'loose_leaf',
    packetSize: '150g',
    packetSizeGrams: 150,
    isImported: true,
    shippingDays: 14,
    originCountry: 'Sri Lanka',
    sku: 'LK-CEYLON-150',
    barcode: '8901234567013',
    warehouseStock: 70,
    reorderLevel: 25,
    purchaseCost: 6.50,
    profitMargin: 115.23,
    isActive: true
  },

  // Herbal Teas (Local Blends - US)
  {
    name: 'Chamomile Flowers Organic',
    description: 'Pure Egyptian chamomile flowers. Calming, apple-like flavor. Caffeine-free.',
    price: 11.99,
    stockQuantity: 85,
    category: 'Herbal Tea',
    imageUrl: 'https://images.unsplash.com/photo-1597318181390-8a9758586c85?w=400',
    teaType: 'loose_leaf',
    packetSize: '50g',
    packetSizeGrams: 50,
    isImported: false,
    shippingDays: 3,
    originCountry: 'USA',
    sku: 'US-CHAM-50',
    barcode: '8901234567014',
    warehouseStock: 90,
    reorderLevel: 30,
    purchaseCost: 5.50,
    profitMargin: 118.00,
    isActive: true
  },
  {
    name: 'Peppermint Leaf Organic',
    description: 'Refreshing peppermint from Oregon. Cooling and digestive. Caffeine-free.',
    price: 9.99,
    stockQuantity: 102,
    category: 'Herbal Tea',
    imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400',
    teaType: 'tea_bags',
    packetSize: '25 bags',
    packetSizeGrams: 50,
    isImported: false,
    shippingDays: 2,
    originCountry: 'USA',
    sku: 'US-PEPPER-25B',
    barcode: '8901234567015',
    warehouseStock: 110,
    reorderLevel: 35,
    purchaseCost: 4.50,
    profitMargin: 122.00,
    isActive: true
  },
  {
    name: 'Lavender Bliss Herbal',
    description: 'Calming lavender blend with chamomile. Perfect bedtime tea. Caffeine-free.',
    price: 12.99,
    stockQuantity: 71,
    category: 'Herbal Tea',
    imageUrl: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400',
    teaType: 'loose_leaf',
    packetSize: '75g',
    packetSizeGrams: 75,
    isImported: false,
    shippingDays: 3,
    originCountry: 'USA',
    sku: 'US-LAVENDER-75',
    barcode: '8901234567016',
    warehouseStock: 75,
    reorderLevel: 25,
    purchaseCost: 6.00,
    profitMargin: 116.50,
    isActive: true
  },
  {
    name: 'Rooibos Red Bush Organic',
    description: 'South African rooibos. Naturally sweet, no caffeine. Rich in antioxidants.',
    price: 10.99,
    stockQuantity: 94,
    category: 'Herbal Tea',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400',
    teaType: 'loose_leaf',
    packetSize: '100g',
    packetSizeGrams: 100,
    isImported: false,
    shippingDays: 3,
    originCountry: 'USA',
    sku: 'US-ROOIBOS-100',
    barcode: '8901234567017',
    warehouseStock: 100,
    reorderLevel: 30,
    purchaseCost: 5.00,
    profitMargin: 119.80,
    isActive: true
  },

  // White Teas
  {
    name: 'Silver Needle White Tea',
    description: 'Premium Chinese white tea. Delicate, sweet, silvery buds. Minimal processing.',
    price: 38.99,
    stockQuantity: 18,
    category: 'White Tea',
    imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400',
    teaType: 'loose_leaf',
    packetSize: '50g',
    packetSizeGrams: 50,
    isImported: true,
    shippingDays: 14,
    originCountry: 'China',
    sku: 'CN-SILVER-50',
    barcode: '8901234567018',
    warehouseStock: 20,
    reorderLevel: 8,
    purchaseCost: 19.00,
    profitMargin: 105.21,
    isActive: true
  },
  {
    name: 'White Peony (Bai Mudan)',
    description: 'Classic Chinese white tea. Floral, fruity notes. Gentle and refreshing.',
    price: 24.99,
    stockQuantity: 35,
    category: 'White Tea',
    imageUrl: 'https://images.unsplash.com/photo-1597318181390-8a9758586c85?w=400',
    teaType: 'loose_leaf',
    packetSize: '75g',
    packetSizeGrams: 75,
    isImported: true,
    shippingDays: 14,
    originCountry: 'China',
    sku: 'CN-PEONY-75',
    barcode: '8901234567019',
    warehouseStock: 40,
    reorderLevel: 12,
    purchaseCost: 12.00,
    profitMargin: 108.25,
    isActive: true
  },

  // Specialty Blends (Local)
  {
    name: 'English Breakfast Classic',
    description: 'Robust blend of Assam and Ceylon. Traditional breakfast tea. Perfect with milk.',
    price: 13.99,
    stockQuantity: 88,
    category: 'Black Tea',
    imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400',
    teaType: 'tea_bags',
    packetSize: '40 bags',
    packetSizeGrams: 80,
    isImported: false,
    shippingDays: 2,
    originCountry: 'USA',
    sku: 'US-ENGBREAKF-40B',
    barcode: '8901234567020',
    warehouseStock: 95,
    reorderLevel: 30,
    purchaseCost: 6.50,
    profitMargin: 115.23,
    isActive: true
  },
  {
    name: 'Earl Grey Supreme',
    description: 'Classic Earl Grey with natural bergamot oil. Aromatic and citrusy.',
    price: 14.99,
    stockQuantity: 76,
    category: 'Black Tea',
    imageUrl: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400',
    teaType: 'both',
    packetSize: '100g',
    packetSizeGrams: 100,
    isImported: false,
    shippingDays: 2,
    originCountry: 'USA',
    sku: 'US-EARLGREY-100',
    barcode: '8901234567021',
    warehouseStock: 80,
    reorderLevel: 25,
    purchaseCost: 7.00,
    profitMargin: 114.14,
    isActive: true
  },
  {
    name: 'Lemon Ginger Wellness',
    description: 'Invigorating blend of green tea, lemon peel, and fresh ginger. Immunity boost.',
    price: 11.99,
    stockQuantity: 67,
    category: 'Green Tea',
    imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400',
    teaType: 'tea_bags',
    packetSize: '20 bags',
    packetSizeGrams: 40,
    isImported: false,
    shippingDays: 2,
    originCountry: 'USA',
    sku: 'US-LEMGINGER-20B',
    barcode: '8901234567022',
    warehouseStock: 70,
    reorderLevel: 22,
    purchaseCost: 5.50,
    profitMargin: 118.00,
    isActive: true
  },
  {
    name: 'Vanilla Rooibos Cream',
    description: 'Dessert tea with rooibos, vanilla, and creamy notes. Naturally sweet, caffeine-free.',
    price: 13.49,
    stockQuantity: 59,
    category: 'Herbal Tea',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400',
    teaType: 'loose_leaf',
    packetSize: '100g',
    packetSizeGrams: 100,
    isImported: false,
    shippingDays: 3,
    originCountry: 'USA',
    sku: 'US-VANROOIB-100',
    barcode: '8901234567023',
    warehouseStock: 65,
    reorderLevel: 20,
    purchaseCost: 6.25,
    profitMargin: 115.84,
    isActive: true
  },

  // More Specialty Options
  {
    name: 'Moroccan Mint Green Tea',
    description: 'Refreshing blend of Chinese gunpowder green tea and spearmint. Traditional Moroccan style.',
    price: 12.99,
    stockQuantity: 72,
    category: 'Green Tea',
    imageUrl: 'https://images.unsplash.com/photo-1597318181390-8a9758586c85?w=400',
    teaType: 'loose_leaf',
    packetSize: '100g',
    packetSizeGrams: 100,
    isImported: false,
    shippingDays: 2,
    originCountry: 'USA',
    sku: 'US-MOROCCMINT-100',
    barcode: '8901234567024',
    warehouseStock: 75,
    reorderLevel: 25,
    purchaseCost: 6.00,
    profitMargin: 116.50,
    isActive: true
  },
  {
    name: 'Turmeric Glow Wellness',
    description: 'Anti-inflammatory blend with turmeric, ginger, cinnamon, and black pepper. Caffeine-free.',
    price: 14.99,
    stockQuantity: 48,
    category: 'Herbal Tea',
    imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400',
    teaType: 'tea_bags',
    packetSize: '20 bags',
    packetSizeGrams: 40,
    isImported: false,
    shippingDays: 3,
    originCountry: 'USA',
    sku: 'US-TURMERIC-20B',
    barcode: '8901234567025',
    warehouseStock: 50,
    reorderLevel: 18,
    purchaseCost: 7.00,
    profitMargin: 114.14,
    isActive: true
  },
  {
    name: 'Butterfly Pea Flower Blue Tea',
    description: 'Stunning blue herbal tea from Thailand. Color-changing with lemon. Antioxidant-rich.',
    price: 16.99,
    stockQuantity: 42,
    category: 'Herbal Tea',
    imageUrl: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400',
    teaType: 'loose_leaf',
    packetSize: '50g',
    packetSizeGrams: 50,
    isImported: true,
    shippingDays: 15,
    originCountry: 'Thailand',
    sku: 'TH-BUTTERFLY-50',
    barcode: '8901234567026',
    warehouseStock: 45,
    reorderLevel: 15,
    purchaseCost: 8.00,
    profitMargin: 112.38,
    isActive: true
  },
  {
    name: 'Hibiscus Berry Blast',
    description: 'Tart hibiscus with mixed berries. Vitamin C rich. Great hot or iced. Caffeine-free.',
    price: 11.49,
    stockQuantity: 81,
    category: 'Herbal Tea',
    imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400',
    teaType: 'tea_bags',
    packetSize: '25 bags',
    packetSizeGrams: 50,
    isImported: false,
    shippingDays: 2,
    originCountry: 'USA',
    sku: 'US-HIBISCUS-25B',
    barcode: '8901234567027',
    warehouseStock: 85,
    reorderLevel: 28,
    purchaseCost: 5.25,
    profitMargin: 118.86,
    isActive: true
  },
  {
    name: 'Chocolate Pu-erh Truffle',
    description: 'Decadent aged pu-erh blended with cocoa nibs and vanilla. Dessert tea with depth.',
    price: 19.99,
    stockQuantity: 36,
    category: 'Black Tea',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400',
    teaType: 'loose_leaf',
    packetSize: '100g',
    packetSizeGrams: 100,
    isImported: true,
    shippingDays: 14,
    originCountry: 'China',
    sku: 'CN-CHOCPUERH-100',
    barcode: '8901234567028',
    warehouseStock: 40,
    reorderLevel: 12,
    purchaseCost: 9.50,
    profitMargin: 110.42,
    isActive: true
  },
  {
    name: 'Yerba Mate Energizer',
    description: 'South American yerba mate. Natural energy boost with vitamins. Earthy, smoky flavor.',
    price: 13.99,
    stockQuantity: 55,
    category: 'Herbal Tea',
    imageUrl: 'https://images.unsplash.com/photo-1597318181390-8a9758586c85?w=400',
    teaType: 'loose_leaf',
    packetSize: '150g',
    packetSizeGrams: 150,
    isImported: true,
    shippingDays: 12,
    originCountry: 'Argentina',
    sku: 'AR-YERBA-150',
    barcode: '8901234567029',
    warehouseStock: 60,
    reorderLevel: 20,
    purchaseCost: 6.50,
    profitMargin: 115.23,
    isActive: true
  },
  {
    name: 'Rose Petal Oolong Romance',
    description: 'Floral oolong tea with rose petals. Romantic, fragrant, and elegant. Perfect gift tea.',
    price: 21.99,
    stockQuantity: 29,
    category: 'Oolong Tea',
    imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400',
    teaType: 'loose_leaf',
    packetSize: '75g',
    packetSizeGrams: 75,
    isImported: true,
    shippingDays: 14,
    originCountry: 'China',
    sku: 'CN-ROSEOOL-75',
    barcode: '8901234567030',
    warehouseStock: 32,
    reorderLevel: 10,
    purchaseCost: 10.50,
    profitMargin: 109.43,
    isActive: true
  }
];

const seedDatabase = async () => {
  try {
    console.log('🌱 Starting to seed tea products...');

    await sequelize.authenticate();
    console.log('✅ Database connected');

    // Clear existing products (optional - comment out if you want to keep existing)
    // await Product.destroy({ where: {} });
    // console.log('🗑️  Cleared existing products');

    // Insert all products
    for (const productData of teaProducts) {
      await Product.create(productData);
      console.log(`✓ Added: ${productData.name}`);
    }

    console.log(`\n🎉 Successfully seeded ${teaProducts.length} tea products!`);
    console.log('\nProduct breakdown:');
    console.log(`- Japanese Teas: 4 (all imported)`);
    console.log(`- Chinese Teas: 8 (all imported)`);
    console.log(`- Indian Teas: 4 (all imported)`);
    console.log(`- Ceylon Teas: 1 (imported)`);
    console.log(`- Local/US Blends: 13`);
    console.log(`\nTotal Imported: ${teaProducts.filter(p => p.isImported).length}`);
    console.log(`Total Local: ${teaProducts.filter(p => !p.isImported).length}`);

    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
};

seedDatabase();
